Create CRUD for employee for the admin view
BC-MAY-21-ROR/kata-06-reloj-checador-m22-krc-t4-reilero-04 pull request #26
Opened 2022-06-03 03:37 UTC by AgustinPalmaM

Created CRUD employees for the admin view

Now we can create, read, update and delete employees

Co-authored-by: @V-Juarez <mytacam78@gmail.com>
Co-authored-by: @OwenLobato <owenlobato@gmail.com>
Co-authored-by: @ruruisu <zaddozgl@gmail.com>

2022-06-03 19:53 UTC, juperameza requested changes

2022-06-03 19:53 UTC, juperameza commented on app/controllers/employees_controller.rb
> +    # @employee.destroy
Code that you don't need delete it

2022-06-03 19:53 UTC, juperameza commented on app/controllers/employees_controller.rb
> +    if @employee.destroy
You should do a logical delete

2022-06-03 22:18 UTC, V-Juarez approved these changes

2022-06-04 12:26 UTC, MatiasDevJam reviewed
this PR has a lot of files, what do you think?

2022-06-06 20:23 UTC, OwenLobato approved these changes
@

2022-06-06 20:25 UTC, OwenLobato submitted a review, later dismissed

2022-06-06 20:33 UTC, YilKanda requested changes
If you are going to change all the files in the check_time_clock folder to root, it is better to do it in a different PR, since only the creation of the employee's CRUD should appear in this PR.

2022-06-06 20:37 UTC, V-Juarez submitted a review, later dismissed

2022-06-06 20:38 UTC, germanruzca commented
Try to follow the @juperameza recommendations

2022-06-06 20:41 UTC, AgustinPalmaM commented on app/controllers/employees_controller.rb
> +    # @employee.destroy
Ok it's done, thanks.

2022-06-06 21:46 UTC, merged