Feature#14 create company branch controller
BC-MAY-21-ROR/kata-06-reloj-checador-m22-krc-t4-reilero-04 pull request #29
Opened 2022-06-06 23:07 UTC by OwenLobato

# Description
- [x] Create views of Stores
-  index
- new
- edit
- show
- [x] Create Stores controller

2022-06-06 23:13 UTC, V-Juarez approved these changes

2022-06-06 23:15 UTC, lucasvidela94 approved these changes
👍  nice job!

2022-06-06 23:17 UTC, HikingCarrot7 submitted a review, later dismissed
LGTM!

2022-06-06 23:18 UTC, germanruzca requested changes

2022-06-06 23:18 UTC, germanruzca commented on app/controllers/stores_controller.rb
> +
Try to add a new line correctly

2022-06-06 23:18 UTC, germanruzca commented on app/views/stores/show.html.erb
> +    <div style="display:flex; flex-direction: column;justify-content: space-between; gap: 10px;">
Try to add styles to the stylesheets files

2022-06-06 23:18 UTC, germanruzca commented on app/views/stores/index.html.erb
> +<div style="display:grid; grid-template-columns: 1fr 1fr;justify-content: space-evenly; gap: 10px">
Try to add styles to the stylesheets files

2022-06-06 23:18 UTC, germanruzca commented on app/views/stores/edit.html.erb
> +<% end %>
New line here

2022-06-06 23:18 UTC, germanruzca commented on app/views/stores/index.html.erb
> +  </a>
Just as a recommendation (you can dismiss this) try to use the button_to helper, including the GET method:
 ` <%= button_to 'Create New Store', new_store_path, method: :get %>`
```suggestion
  <%= button_to 'Create New Store', new_store_path, method: :get %>
```

Just a recommendation for future implementations

2022-06-06 23:25 UTC, OwenLobato commented on app/controllers/stores_controller.rb
> +
Done

2022-06-07 00:03 UTC, AgustinPalmaM approved these changes
LGTM

2022-06-07 00:05 UTC, germanruzca submitted a review, later dismissed
LGTM

2022-06-07 01:02 UTC, juperameza requested changes

2022-06-07 01:02 UTC, juperameza commented on app/controllers/stores_controller.rb
> +    if @store.destroy
You should do a logical delete

2022-06-07 01:28 UTC, V-Juarez approved these changes

2022-06-07 20:05 UTC, YilKanda reviewed
Try to keep the issue as simple as possible, that is, if you make a rubocop correction, only the files corresponding to your file should appear corrected.

My suggestion is that if you want to correct all the files with one or more Linters, it is preferable that you indicate it in a separate PR.

2022-06-07 20:53 UTC, V-Juarez submitted a review, later dismissed

2022-06-07 22:10 UTC, ruruisu commented on app/controllers/stores_controller.rb
> +    if @store.destroy
done

2022-06-07 22:12 UTC, ruruisu commented on app/helpers/employees_helper.rb
>  end
done, removed the file from the project

2022-06-07 22:12 UTC, ruruisu commented on app/views/employees/show.html.erb
> +    </div>
done

2022-06-07 22:12 UTC, ruruisu commented on app/views/stores/show.html.erb
> +</div>
done

2022-06-07 22:43 UTC, V-Juarez approved these changes

2022-06-07 23:07 UTC, juperameza approved these changes
LGTM

2022-06-08 00:34 UTC, AgustinPalmaM approved these changes
LGTM

2022-06-08 00:34 UTC, merged